# Generated by Django 2.2 on 2020-11-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0003_auto_20201119_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submiter', to='exapp.User'),
        ),
    ]
